trigger:
  branches:
    include:
      - main
  paths:
    include: 
      - pipeline-samples/**
    exclude:
      - 01-Project/**
      - 02-Project/**
      - 03-Project/**
      - 04-Project/**
pool:
  name: 'self-hosted'
stages:
  - stage: validate
    jobs:
      - job: terraform_deploy
        steps:
          - task: TerraformInstaller@1 # installs terraform
            inputs:
              terraformVersion: '1.6.6'
          - task: TerraformTask@5 # terraform init
            inputs:
              provider: 'azurerm'
              command: 'init'
              workingDirectory: '$(System.DefaultWorkingDirectory)/pipeline-sample/'
              backendServiceArm: 'az-ado-identity'
              backendAzureRmResourceGroupName: 'tf-backend-rg'
              backendAzureRmStorageAccountName: 'tfazbackendstore2709'
              backendAzureRmContainerName: 'tf-backend'
              backendAzureRmKey: 'statefile.tfstate'
              backendAzureRmUseEntraIdForAuthentication: false
          - task: TerraformTask@5 # terraform validate
            inputs:
              provider: 'azurerm'
              command: 'validate'
              workingDirectory: '$(System.DefaultWorkingDirectory)/pipeline-sample/'
                                
          - task: TerraformTask@5 # terraform destroy
            inputs:
              provider: 'azurerm'
              command: 'destroy'
              workingDirectory: '$(System.DefaultWorkingDirectory)/pipeline-sample/'
              commandOptions: '-var-file="vars.tfvars" -auto-approve'
              environmentServiceNameAzureRM: 'az-ado-identity'
              backendAzureRmUseEntraIdForAuthentication: false