# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - main
  paths:
    include: 
      - pipeline-samples/**
    exclude:
      - 01-Project/**
      - 02-Project/**
      - 03-Project/**
      - 04-Project/**
pool:
  name: self-hosted

stages:
  - stage: validate
    jobs:
      - job: InstallJob
        steps:
          - task: TerraformInstaller@1
            inputs:
              terraformVersion: '1.6.6'
      - job: InitJob
        dependsOn: InstallJob
        condition: succeeded()
        steps:
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'init'
              workingDirectory: '$(System.DefaultWorkingDirectory)/pipeline-sample'
              backendServiceArm: 'adomanagedidentity'
              backendAzureRmResourceGroupName: 'tf-backend-rg'
              backendAzureRmStorageAccountName: 'tfazbackendstore2709'
              backendAzureRmContainerName: 'tf-backend'
              backendAzureRmKey: 'devstatefile.tfstate'

      - job: ValidateJob
        dependsOn: InitJob
        condition: succeeded()
        steps:
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'validate'
              workingDirectory: '$(System.DefaultWorkingDirectory)/pipeline-sample'
              environmentServiceNameAzureRM: 'adomanagedidentity'

  - stage: deployment
    dependsOn: validate
    condition: succeeded()
    jobs:
      - job: PlanJob
        steps:
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'plan'
              workingDirectory: '$(System.DefaultWorkingDirectory)/pipeline-sample'
              commandOptions: '-var-file="vars.tfvars"'
              environmentServiceNameAzureRM: 'adomanagedidentity'
      - job: ApplyJob
        steps:
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'apply'
            workingDirectory: '$(System.DefaultWorkingDirectory)/pipeline-sample'
            commandOptions: '-var-file="vars.tfvars"'
            environmentServiceNameAzureRM: 'adomanagedidentity'

          
