# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - main
  paths:
    include: 
      - pipeline-samples/**
    exclude:
      - 01-Project/**
      - 02-Project/**
      - 03-Project/**
      - 04-Project/**
pool:
  name: self-hosted

stages:
  - stage: validate
    jobs:
      - job: tf_install
        steps:
          - task: TerraformInstaller@1
            inputs:
              terraformVersion: '1.11.0'
      - job: tf_validate
        steps:
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'validate'
              workingDirectory: '$(System.DefaultWorkingDirectory)/pipeline-sample'
      - job: tf_init
        steps:
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'init'
              workingDirectory: '$(System.DefaultWorkingDirectory)/pipeline-sample'
              backendServiceArm: 'PAID Monthly(9a11755d-a926-4ef7-b329-2f1a3dc2e9c5)'
              backendAzureRmResourceGroupName: 'tf-backend-rg'
              backendAzureRmStorageAccountName: 'tfazbackendstore2709'
              backendAzureRmContainerName: 'tf-backend'
              backendAzureRmKey: 'devstatefile.tfstate'
  - stage: deployment
    condition: succeeded()
    jobs:
      - job: tf_plan
        steps:
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'plan'
              workingDirectory: '$(System.DefaultWorkingDirectory)/pipeline-sample'
              commandOptions: '-var-file="vars.tfvars"'
              environmentServiceNameAzureRM: 'PAID Monthly(9a11755d-a926-4ef7-b329-2f1a3dc2e9c5)'
      - job: tf_apply
        steps:
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'apply'
            workingDirectory: '$(System.DefaultWorkingDirectory)/pipeline-sample'
            environmentServiceNameAzureRM: 'PAID Monthly(9a11755d-a926-4ef7-b329-2f1a3dc2e9c5)'

          
